### PR TITLE
Edly 2414 Upgrade Ecommerce to Juniper (Part1)

### PR DESCRIPTION
**Pull request by iam-mhaseeb**
Description: This PR is 1st part for the up-gradation of  Ecommerce service to juniper and merges `juniper.master` into our `develop-multisite` branch.

This PR solves the following conflicts:
#### Conflicts in migrations
  - Core app:
     - 0048_siteconfiguration_edly_client_theme_branding_settings.py
     - 0048_siteconfiguration_hubspot_secret_key.py
     - 0049_auto_20200414_0843.py
     - 0049_ecommercefeaturerole_ecommercefeatureroleassignment.py
     - 0050_add_course_payments_flag_in_siteconfiguration.py
     - 0050_add_specific_ecommerce_roles.py
  -  Invoice app
     - 0007_historicalinvoice.py (Due to 0051_ecommercefeatureroleassignment_enterprise_id depdency)
 
#### Removes deprecations
 - Removes (from rest_framework import filters) and introduces (from django_filters.rest_framework import DjangoFilterBackend) in the following files:
   - ecommerce/extensions/api/v2/views/coupons.py
   - ecommerce/subscriptions/api/v2/views.py
 - Removes (from rest_framework.decorators import list_route) and introduces (from rest_framework.decorators import action) in the following files:
   - ecommerce/subscriptions/api/v2/views.py
 - Removes (object) from middleware class and introduces (MiddlewareMixin) in the following files:
   - ecommerce/extensions/edly_ecommerce_app/middleware.py
 - Removes Journal from edly themes
   - edly-edx-themes/st-lutherx/ecommerce/st-lutherx-ecommerce/templates/edx/partials/_administration_menu.html 
   - edly-edx-themes/st-normanx/ecommerce/st-normanx-ecommerce/templates/edx/partials/_administration_menu.html
   - edly-edx-themes/adroit/ecommerce/adroit-ecommerce/templates/edx/partials/_administration_menu.html 
    
#### Fixes imports issues at the following files
   - ecommerce/extensions/payment/utils.py

#### Resolves simple conflicts in the following files
   - ecommerce/static/js/views/course_form_view.js

#### Convert old python unicode to str in the following files
   - ecommerce/extensions/payment/processors/authorizenet.py
   - ecommerce/extensions/catalogue/utils.py

#### Fixes tests in the following files
   - ecommerce/core/tests/test_context_processors.py
       - CoreContextProcessorTests
   - Disable edlly organization middleware in following files
      - ecommerce/coupons/tests/test_views.py
      - ecommerce/courses/tests/test_views.py
      - ecommerce/credit/tests/test_views.py
      - ecommerce/programs/tests/test_views.py
      - ecommerce/programs/tests/test_offer.py
      - ecommerce/tests/test_urls.py
      - ecommerce/extensions/basket/tests/test_views.py
      - ecommerce/extensions/checkout/tests/test_views.py
      - ecommerce/extensions/payment/tests/views/test_apple_pay.py
      - ecommerce/extensions/payment/tests/views/test_authorizenet.py
      - ecommerce/extensions/payment/tests/views/test_cybersource.py
      - ecommerce/extensions/payment/tests/views/test_paypal.py
      - ecommerce/extensions/payment/tests/views/test_sdn.py
      - ecommerce/extensions/payment/tests/views/test_stripe.py
      - ecommerce/extensions/api/v2/tests/views/test_assignmentemail.py
      - ecommerce/extensions/api/v2/tests/views/test_baskets.py
      - ecommerce/extensions/api/v2/tests/views/test_catalog.py
      - ecommerce/extensions/api/v2/tests/views/test_checkout.py
      - ecommerce/extensions/api/v2/tests/views/test_coupons.py
      - ecommerce/extensions/api/v2/tests/views/test_courses.py
      - ecommerce/extensions/api/v2/tests/views/test_enterprise.py
      - ecommerce/extensions/api/v2/tests/views/test_orders.py
      - ecommerce/extensions/api/v2/tests/views/test_partners.py
      - ecommerce/extensions/api/v2/tests/views/test_payments.py
      - ecommerce/extensions/api/v2/tests/views/test_products.py
      - ecommerce/extensions/api/v2/tests/views/test_providers.py
      - ecommerce/extensions/api/v2/tests/views/test_publication.py
      - ecommerce/extensions/api/v2/tests/views/test_refunds.py
      - ecommerce/extensions/api/v2/tests/views/test_retirement.py
      - ecommerce/extensions/api/v2/tests/views/test_stockrecords.py
      - ecommerce/extensions/api/v2/tests/views/test_user_management.py
      - ecommerce/extensions/api/v2/tests/views/test_vouchers.py

JIRA:
https://edlyio.atlassian.net/browse/EDLY-2414

### CODE REVIEW

**Review by zubair-arbi — APPROVED** [review]
Changes looks good 👍 
Just make sure our payment flows and custom functionalities e.g. disabling paid courses mode via site configuration while publishing a course etc

**Review by asadmanzoor93 — COMMENTED** [review]
@iam-mhaseeb did you verify unit tests are working fine after the upgrade? and also verify python version requirements for Juniper and test accordingly.

**Comment by iam-mhaseeb** [comment]
> @iam-mhaseeb did you verify unit tests are working fine after the upgrade? and also verify python version requirements for Juniper and test accordingly.

This is the first part this is simply merging juniper master into develop-multisite. We would do compatibility fixes and unit tests fixes in upcoming pull requests if required.

**Review by burhandodhy — APPROVED** [review]

**Review by asadmanzoor93 — APPROVED** [review]
@iam-mhaseeb Kindly `squash` commits before merging.

**Pull request merged**
